### ISSUE TITLE
Issues on Debian 10

### ISSUE THREAD

**Issue by jbiancot** [spring-projects-experimental/spring-graal-native#110]
Hi there,

I tried on Debian 10 after installing some dependencies and I could finished a sucessful "Hello World"

I have attached the output.txt.

Any clue?

[output.txt](https://github.com/spring-projects-experimental/spring-graal-native/files/4525607/output.txt)

**Comment by jbiancot** [comment]
Actually Tomcat runs fine. I am still testing. Keep the net inform.

**Comment by aclement** [comment]
I've been running things on ubuntu and it is working ok.  Commandlinerunner sample working ok for you? That is a good test beyond a very basic hello world because it is the simplest app that includes spring configuration.

**Comment by sdeleuze** [comment]
@jbiancot Any update?

**Comment by jbiancot** [comment]
I can run successfully the one that has a Tomcat, but I realize it is super simple, like 2 classes and one point. I tried to build an more real app, using Spring Boot v2.2.x, and I used to build it with Gradle 4.10, then I tried to remove some code - dependencies to make it smaller but it failed miserably.

**Comment by sdeleuze** [comment]
Yeah we are not here yet as explained [here](https://github.com/spring-projects-experimental/spring-graal-native#scope-and-status) and Spring Boot 2.2 is not supported, only 2.3 M4 at this time, so I will close this issue.

**Comment by jbiancot** [comment]
Ok, I will give it a try to 2.3M4 or better 2.3.0RC1 ??
