### ISSUE TITLE
Errors when running samples

### ISSUE THREAD

**Issue by brutalbrian** [spring-projects-experimental/spring-graal-native#128]
Hi,
I've followed the "getting started" guide to the letter, but keep getting the following critical errors when the build script gets to the native image generation:

Warning: class initialization of class org.springframework.boot.validation.MessageInterpolatorFactory failed with exception java.lang.NoClassDefFoundError: javax/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.validation.MessageInterpolatorFactory to explicitly request delayed initialization of this class.
Number of types dynamically registered for reflective access: #839
[commandlinerunner:329806]     analysis:  10,379.69 ms,  1.69 GB
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager was unintentionally initialized at build time. To see why org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager got initialized use -H:+TraceClassInitialization
........................................................................................... (additional Spring classes initialized at build time)

Any ideas?

**Comment by sdeleuze** [comment]
My guess is that you are using GraalVM native 20.0.0 not 20.1-dev, see instructions on https://github.com/spring-projects-experimental/spring-graal-native#baseline for building samples against `master` using GraalVM dev builds or containers.
