### ISSUE TITLE
 Optimize image size (step 1)

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graal-native#16]
For now without modification on Framework / Boot. More optimizations will come later.

**Comment by aclement** [comment]
just noting optimization branch merged, image sizes down across the board although without automated tests on all samples, some samples will likely have broken (the key ones: webflux-netty/springmvc-tomcat are fine)

**Comment by sdeleuze** [comment]
Based on our latest discussions, maybe we should turn this issue into focusing the feature on optimizations and create a new one for leveraging the tracing agent once fixed in GraalVM `master`?

**Comment by sdeleuze** [comment]
With the work done on `jafu` and `jafu-webmvc` samples and the related substitution created in the feature, I think we can consider this issue as done. We will create subsequent issues as needed.
