### ISSUE TITLE
proxy and reflection settings are insufficient for Pet Clinic

### ISSUE THREAD

**Issue by tiwatsuka** [spring-projects-experimental/spring-graal-native#23]
The Pet Clinic application can be built as Native Image.
However, when I click the "Add New Pet" button in "Owner Information" page, an internal error has occurred.

The settings seem to be insufficient.
After I added `org.springframework.web.bind.annotation.ModelAttribute` and `org.springframework.format.annotation.DateTimeFormat` to both `proxies.json` and `reflect.json`, it works fine.

**Comment by aclement** [comment]
We are going through some refactorings and slowly migrating to new graal. The focus has been on commandlinerunner/webflux-netty/springmvc-tomcat samples - I hadn't got a chance to look at petclinic yet. Let me try what you suggest to get that behaving, thanks for the info!

**Comment by sdeleuze** [comment]
Fixed on `upgrade_19_3` which is about to merged in `master`, thanks for providing compatibility hints.
