### ISSUE TITLE
Revisit feature parameter names to avoid confusion with native-image ones

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graal-native#62]
Example : `--verbose` versus `-Dverbose=true`. Maybe we should use a prefix... Just for this one or for others as well?

**Comment by aclement** [comment]
Yes I'd been thinking about this too. I want something relatively short though.

**Comment by sdeleuze** [comment]
`spring.` prefix could clash with Spring Boot, so maybe `spring.graal.`? `spring.graal-native.` is more accurate but longer so maybe less your cup of tea...  If we take this opportunity to align with Spring Boot application properties conventions, that would give us:

- `-Dspring.graal.remove-unused-autoconfig`
- `-Dspring.graal.verbose`
- `-Dspring.graal.avoid-logback`
- `-Dspring.graal.remove-yaml-support`
- `-Dspring.graal.dump-config=/tmp/dump.txt`
- `-Dspring.graal.missing-selector-hints=warning`

I would maybe also take this opportunity to rationalize a little bit and rename `avoid-logback` to `skip-logback` and `remove-yaml-support` to `skip-yaml`.

Any thoughts?

**Comment by wilkinsona** [comment]
If you are concerned about a clash with Spring Boot, then I think using a `spring.graal` prefix should be avoided. I can't imagine what they might be, but it we were to introduce any Graal-specific properties to Spring Boot, `spring.graal` would be the natural prefix for them to have.

**Comment by sbrannen** [comment]
Well, core Spring also has some system properties that use the `spring.` prefix, albeit nothing comparable to the number of properties supported by Spring Boot.

So one could imagine that Spring Framework might introduce `spring.graal` properties at some point as well. I'm not saying that's very likely, but it is possible.

So perhaps system properties specific to the Spring GraalVM native image feature need a more description prefix.

But of course... naming is hard!

**Comment by sdeleuze** [comment]
Is it really an issue since this project is like a Spring Boot + Graal incubator? If there is GraalVM native support in Boot the related feature (or hopefully the whole module) should just live in Boot and be removed from here.

**Comment by snicoll** [comment]
I guess that's what Andy meant by 

> If you are concerned about a clash with Spring Boot

If that's experimental, another solution is to add that somewhere in the key to make it explicit it's not the final thing. For reference, we had an r2dbc experimental support that tried to stick as much as possible with the target (so with `spring.r2dbc.*` properties). In the end, some code was changed and some properties were removed or renamed but the basic foundation helped users to migrate to the non experimental version.

I think this is a concern if we believe the result of this work is not going to end up in Spring Boot proper.

**Comment by sdeleuze** [comment]
We could use something like `spring.experimental.graal.*`, but I would personnally prefer using just `spring.graal.*` since our target is to produce something that could be integrated in Spring Boot. Obviously we are not at this stage yet but gradually modifying this project toward that goal (including properties names) would make sense with related migration notes IMO.

**Comment by wilkinsona** [comment]
That's fine by me. Sorry, I should have been clearer above. I was just responding to "`spring.` prefix could clash with Spring Boot".
