### ISSUE TITLE
Auto config warning in native build generation

### ISSUE THREAD

**Issue by dheeraj29** [spring-projects-experimental/spring-graal-native#7]
I am finding lot of warning that reflect.json not found or so when running commanlinerunner sample with compile.sh

Is there a workaround for this or any plan's to avoid?

[output.txt](https://github.com/spring-projects-experimental/spring-graal-feature/files/3639465/output.txt)

**Comment by sdeleuze** [comment]
This is just temporary, we indeed plan to remove most of `reflect.json` with feature improvements.

**Comment by aclement** [comment]
A lot of warnings have now been removed unless running in verbose mode. They were proving very useful to us whilst developing things but I agree it is a quite a bit of noise. The default mode should be friendlier now (there are still a few to remove, but there are far less overall).

**Comment by sdeleuze** [comment]
I think we now have a reasonable amount of warning so I close this issue.
