### ISSUE TITLE
Provide a spring.graal.mode for init + ressources

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graal-native#86]
Such mode would be useful for use cases like Spring Fu applications.

**Comment by aclement** [comment]
by 'resources' I presume you mean the curated list in `resources.json` (in the configuration submodule). This is for when you don't use the agent, just the feature but don't need the reflective part?

**Comment by sdeleuze** [comment]
Yes, which is mostly what we need for Spring functional applications. A few reflective entries are still needed but I think these can be provided on Spring Fu side since code analysis does most of the work.

**Comment by sdeleuze** [comment]
Maybe we could rename `initialization-only` mode to `initialization` or `init` to make it shorter and support specifying `-Dspring.graal.mode=init,resource`, the `default` mode being replaced by `-Dspring.graal.mode=init,resource,reflect,proxy` (longer but that does not really matter since that will be the default)?

**Comment by aclement** [comment]
I quite like that option breakdown, yep. Do we need a name for `init` with `limited-reflection-analysis-to-backup-the-basic-agent-collected-config` ?  I'm struggling a bit with a name for it. `component-reflect`, hmm.

**Comment by aclement** [comment]
Although there are some subtleties to think through. For example does `proxy` mean just the proxies in the proxies.json file embedded in the feature or does it also include the proxies we add during analysis of the components? (supporting repositories for example).  Maybe we're considering it at the wrong level and the options should be a higher level interpretation. (e.g. turn on/off auto-configuration analysis), hmm.

**Comment by sdeleuze** [comment]
As just discussed, I like your idea of having something more high level.

Something like:
 - `agent` = `initialization-only` with a more meaningful name for the end user
-  `hybrid` is the mode introduced by https://github.com/spring-projects-experimental/spring-graal-native/issues/103 using agent for autoconfig and feature for user components like `@Controller`
- `feature` is the "regular" mode that does not require agent and configure reflection for typical annotation based Boot apps
- `functional` is tailored for very minimal reflection and mainly init + resources (without *.class) for Spring Fu style application. I can take care of the implementation of that one.

**Comment by aclement** [comment]
These modes are all in, the docs are updated. The hybrid mode needs work, which will be done under #103.  The jafu samples are switched to using the functional mode, but may need more changes to take advantage if they still include resource configuration.
